spring.application.name=beer-catalogue-api

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/mydatabase}
spring.datasource.username=${DB_USER:myuser}
spring.datasource.password=${DB_PASSWORD:secret}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

api.prefix=/api/v1