{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "beer-catalogue.serviceAccountName" . }}
  labels:
    {{- include "beer-catalogue.labels" . | nindent 4 }}
  # In real prod you would annotate this with an IAM role (IRSA) so the pod
  # reads the DB password straight from AWS Secrets Manager instead of a k8s Secret:
  # annotations:
  #   eks.amazonaws.com/role-arn: arn:aws:iam::<account>:role/beer-catalogue-sa
  {{- end -}}