image:
  repository: ghcr.io/ndnkmrz/beer-catalogue-api
  tag: "latest"

replicaCount: 2

database:
  url: "jdbc:postgresql://beer-catalogue-db.c1i8w202y7iw.eu-south-2.rds.amazonaws.com:5432/postgres"
  username: "postgres"
  existingSecret: "beer-db-credentials"
  secretPasswordKey: "db-password"

service:
  type: LoadBalancer